name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Verificar la versión de Java  instalada
      - name: Check Java version build
        run: java -version

      # Verificar la versión de Maven y la configuración de Java que está usando
      - name: Check Maven Java version
        run: mvn -v

      - name: Build with Maven
        run: mvn clean install -DskipTests=true -X

      - name: Run Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Este job se ejecutará después de que el job de build sea exitoso
    if: github.ref == 'refs/heads/main'  # Solo despliega si es la rama main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Verificar la versión de Java instalada
      - name: Check Java version deploy
        run: java -version

      - name: Create PEM file from secret
        run: |
          echo "$AWS_PEM_FILE" > /tmp/shopsqs.pem
          chmod 400 /tmp/shopsqs.pem
        env:
          AWS_PEM_FILE: ${{ secrets.AWS_PEM_FILE }}

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"  # Cambia esto a tu región
        run: |
          # Instalar AWS CLI
          sudo apt-get install awscli
          
          # Dar permisos de ejecución al script de despliegue
          chmod +x ./deploy_script.sh

          # Desplegar la aplicación
          ./deploy_script.sh /tmp/shopsqs.pem
